/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.bean.Cd;
import model.bean.Cliente;
import model.dao.cdDAO;
import model.dao.clienteDAO;

/**
 *
 * @author aluno-285
 */
public class ViewJTable_Cd extends javax.swing.JFrame {

    /**
     * Creates new form ViewJTable_CARRO
     */
    public ViewJTable_Cd() {
        initComponents();
        setIcon();
        DefaultTableModel modelo = (DefaultTableModel) jTCd.getModel();
        jTCd.setRowSorter(new TableRowSorter(modelo));
        

        readJTable();
    }
    
     public void readJTable() {
        
        DefaultTableModel modelo = (DefaultTableModel) jTCd.getModel();
        modelo.setNumRows(0);
        cdDAO cdao = new cdDAO();

        for (Cd c : cdao.read()) {

            modelo.addRow(new Object[]{
                c.getId_cd(),
                c.getNome(),
                c.getPreco(),
                c.getDescricao(),
                c.getQuantidade()
                
               
            });

        }

    }
     
     public void readJTableForTi(String ti) {
        
        DefaultTableModel modelo = (DefaultTableModel) jTCd.getModel();
        modelo.setNumRows(0);
        cdDAO cdao = new cdDAO();

        for (Cd c : cdao.readForTi(ti)) {

            modelo.addRow(new Object[]{
                c.getId_cd(),
                c.getNome(),
                c.getPreco(),
                c.getDescricao(),
                c.getQuantidade()
                
               
            });

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        JLabal = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTCd = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtTitulo = new javax.swing.JTextField();
        txtPreco = new javax.swing.JTextField();
        txtQuantidade = new javax.swing.JTextField();
        txtDescricao = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        txtTitulo_pesquisa = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setText("Alterar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 170, 89, -1));

        jButton3.setText("Excluir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 230, 89, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Cadastrar CDs");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 137, 32));

        JLabal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JLabal.setForeground(new java.awt.Color(240, 240, 240));
        JLabal.setText("Título:");
        getContentPane().add(JLabal, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 47, 22));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Preço:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, -1, -1));

        jTCd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Título", "Preço", "Descrição", "Quantidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTCd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTCdMouseClicked(evt);
            }
        });
        jTCd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTCdKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTCd);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 770, 350));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Descrição:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("Quantidade:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 126, -1));

        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 110, 90, -1));
        getContentPane().add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 170, 30));
        getContentPane().add(txtPreco, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 112, 170, 30));
        getContentPane().add(txtQuantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 180, 170, 30));
        getContentPane().add(txtDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 170, 30));

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton4.setText("Pesquisar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 90, -1));

        txtTitulo_pesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTitulo_pesquisaActionPerformed(evt);
            }
        });
        getContentPane().add(txtTitulo_pesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 120, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fundo 04.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 3, 1000, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        Cd c = new Cd();
        cdDAO dao = new cdDAO();

        c.setNome(txtTitulo.getText());
        c.setPreco(txtPreco.getText());
        c.setDescricao(txtDescricao.getText());
        c.setQuantidade(Integer.parseInt(txtQuantidade.getText()));
        
        dao.create(c);

        txtTitulo.setText(null);
        txtPreco.setText(null);
        txtDescricao.setText(null);
        txtQuantidade.setText(null);
        

        readJTable();
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    int sair = JOptionPane.showConfirmDialog(null,"Tem certeza de que deseja excluir?");
    int sairl = Integer.bitCount(sair);
    
    if(sairl == 0){    
          if (jTCd.getSelectedRow() != -1) {

            Cd c = new Cd();
            cdDAO dao = new cdDAO();

            c.setId_cd((int) jTCd.getValueAt(jTCd.getSelectedRow(), 0));
            
            dao.delete(c);

            txtTitulo.setText(null);
            txtPreco.setText(null);
            txtDescricao.setText(null);
            txtQuantidade.setText(null);
           

            readJTable();

        } else {
            JOptionPane.showMessageDialog(null, "Selecione um carro para excluir.");
        }
    }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
         if (jTCd.getSelectedRow() != -1) {

            Cd c = new Cd();
            cdDAO dao = new cdDAO();
            
            c.setNome(txtTitulo.getText());
            c.setPreco(txtPreco.getText());
            c.setDescricao(txtDescricao.getText());
            c.setQuantidade(Integer.parseInt(txtQuantidade.getText()));
            
             c.setId_cd((int) jTCd.getValueAt(jTCd.getSelectedRow(), 0));
             
            dao.update(c);

            txtTitulo.setText(null);
            txtPreco.setText(null);
            txtDescricao.setText(null);
            txtQuantidade.setText(null);
            

            readJTable();

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTCdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTCdMouseClicked
       
         if (jTCd.getSelectedRow() != -1) {

            txtTitulo.setText(jTCd.getValueAt(jTCd.getSelectedRow(), 1).toString());
            txtPreco.setText(jTCd.getValueAt(jTCd.getSelectedRow(), 2).toString());
            txtDescricao.setText(jTCd.getValueAt(jTCd.getSelectedRow(), 3).toString());
            txtQuantidade.setText(jTCd.getValueAt(jTCd.getSelectedRow(), 4).toString());
            

        }
        
    }//GEN-LAST:event_jTCdMouseClicked

    private void jTCdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTCdKeyReleased
        
        if (jTCd.getSelectedRow() != -1) {

            txtTitulo.setText(jTCd.getValueAt(jTCd.getSelectedRow(), 1).toString());
            txtPreco.setText(jTCd.getValueAt(jTCd.getSelectedRow(), 2).toString());
            txtDescricao.setText(jTCd.getValueAt(jTCd.getSelectedRow(), 3).toString());
            txtQuantidade.setText(jTCd.getValueAt(jTCd.getSelectedRow(), 4).toString());
           

        }
        
    }//GEN-LAST:event_jTCdKeyReleased

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        readJTableForTi(txtTitulo_pesquisa.getText());

    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtTitulo_pesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTitulo_pesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTitulo_pesquisaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewJTable_Cd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewJTable_Cd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewJTable_Cd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewJTable_Cd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewJTable_Cd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabal;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTCd;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtPreco;
    private javax.swing.JTextField txtQuantidade;
    private javax.swing.JTextField txtTitulo;
    private javax.swing.JTextField txtTitulo_pesquisa;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
      setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("snake21.png")));
    }
}
